twig:
    default_path: '%kernel.project_dir%/templates'

    # activation du th√®me Boostrap 5 pour les formulaires
    form_themes: ['bootstrap_5_layout.html.twig']


when@test:
    twig:
        strict_variables: true
